version: '3'
services:
  
  app:
    
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresdb/masma?schema=public
      - MAGIC_LINK_SECRET_KEY= 
      - PUSHER_APP_ID=
      - PUSHER_APP_KEY=
      - PUSHER_APP_SECRET=
      - PUSHER_APP_CLUSTER=
      - NEXT_PUBLIC_MAGIC_LINK_API_KEY=
      - WYRE_SECRET_KEY=TEST-SK
      - WYRE_ACCOUNT_KEY=AC_
      - WYRE_ORDER_URL=https://api.testwyre.com/v3/orders/reserve
      - NEXT_PUBLIC_CHAIN_ID=
  postgres:
    container_name: postgresdb
    image: postgres:12.3
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: masma
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/app/public
    depends_on:
      - app

volumes:
  postgres_data: